### ISSUE TITLE
C++11?

### ISSUE THREAD

**Issue by martonmiklos** [cornelius/kode#17]
Hi @dfaure-kdab @cornelius 

Do you have any objections about using C++11 only code in the kode?

**Comment by cornelius** [comment]
I personally am fine with using C++11. I have a hard time coming up with reasons why that could be an issue.

**Comment by dfaure** [comment]
No objection. Good timing, I just enabled it in KDSoap. Le 28 nov. 2018 20:11, Miklós Márton <notifications@github.com> a écrit :Hi @dfaure-kdab @cornelius

Do you have any objections about using C++11 only code in the kode?

**Comment by martonmiklos** [comment]
Hi David,
Thanks for the comment, I will close the issue and use C++11 in new codes.
