### ISSUE TITLE
Sunsetting kwsdl?

### ISSUE THREAD

**Issue by martonmiklos** [cornelius/kode#41]
Hello @cornelius,

I came across the kwsdl folder in the repo recently, and I have started to think about whether it would makes sense to remove it. It still depends on the KDE3? development libraries, and I think the KDAB's kdsoap  does the same job with better support.
Could you please let me know your opinion about this!

**Comment by cornelius** [comment]
I have no issues with retiring kwsdl. I don't think anybody is still using this code.

**Comment by martonmiklos** [comment]
Thanks for the answer, I have removed the code and references from the documentation in #42 . Do you have any information about the usage of the kxforms in the wild?
