### ISSUE TITLE
Replace the KDSOAP_DEBUG_PARSER debug method with QLoggingCategory

### ISSUE THREAD

**Issue by martonmiklos** [cornelius/kode#44]
QLoggingCategory is more elegant I think.

**Comment by dfaure-kdab** [comment]
That's for sure. This code is from qt4 times before QLoggingCategory existed.

**Comment by martonmiklos** [comment]
Aye! Btw it is also present in the KDSOAP's parser. If I got to this point to fix this I will submit a PR there as well.
