### ISSUE TITLE
Local include seems to be broken

### ISSUE THREAD

**Issue by Siltyx** [cornelius/kode#55]
Hi,
When i try to compile a schema using a local includes i get an error.
_including schema at /opendrive_16_junction.xsd_
Then it says _Download failed, unknown protocol ""_ 

As a hotfix, i inserted:
```
    target = url.toString();
    target.remove(0,1); //remove / at the beginning
    return true;
```
at the beginning of `bool FileProvider::get(const QUrl &url, QString &target)`
This seems to work.
So i guess local paths are mistaken for urls?!?

Kind regards,
Sebastian

**Comment by martonmiklos** [comment]
Well on Linux the "/opendrive_16_junction.xsd" could be a valid file path. Can you post the problematic XSD?
